### ISSUE TITLE
Writing map state to a replay

### ISSUE THREAD

**Issue by StoneT2000** [glmcdona/LuxPythonEnvGym#20]
Just remembered due to how the visualizer is setup, it will require the initial map state (the only thing that is based on seed)

Adding this issue so I remember to have the visualizer parse the initial map first.

This write map state will also be necessary for some basic tests to compare outputs of matches

**Comment by glmcdona** [comment]
Good find. Yeah, that will be an issue meaning we can't render replays in your nice visualizer unless we fix that map generation random generation seed issue.

**Comment by StoneT2000** [comment]
Oh I'm saying I can have the visualizer actually just read in an initial map state instead ( I can add this)
