### ISSUE TITLE
Note, specs are being changed a bit in next version

### ISSUE THREAD

**Issue by StoneT2000** [glmcdona/LuxPythonEnvGym#29]
Just leaving this up. I'm busy with updating our engine on a few things.

Things to note
- Mining has changed. It's now symmetric and does it by processing "mining requests"
- Wood Growth, City Upkeep and adjacency bonus have changed
- Carts probably will be building roads at a rate of 0.75 now.

**Comment by glmcdona** [comment]
Thanks for the heads up!
