### ISSUE TITLE
Could there be a place to load in models?

### ISSUE THREAD

**Issue by goforks12** [glmcdona/LuxPythonEnvGym#43]
Hey, Thanks for the wrapper! Could there be a way to load in our checkpoints of our models?

**Comment by royerk** [comment]
Hey @goforks12 

I am currently using this in the `train.py` script:

```python3
def get_command_line_arguments():
    ...
    parser.add_argument('--path', type=str, default=None)   # get the path to a checkpoint
    ...
```

```python3
def train(args):
    ...
    if args.path:
        model = PPO.load(args.path)
        model.set_env(env=env)
    else:
        model = PPO(...)
    ...
```

I am not 100% sure it works as intended. If you could confirm too that it works then I can make the PR.

**Comment by royerk** [comment]
@glmcdona solved!
