### ISSUE TITLE
GameMap.width and GameMap.height stay the same during training

### ISSUE THREAD

**Issue by nosound2** [glmcdona/LuxPythonEnvGym#74]
[This logic](https://github.com/glmcdona/LuxPythonEnvGym/blob/4c68c5f31e2778c9d688d842741a9f61f7f3052b/luxai2021/game/game_map.py#L85) in GameMap results in same values for `GameMap.width` and `GameMap.height` for the whole training in my runs. Can you reproduce? Why is it like this? In general, I would try to refrain from modifying config in this code.

**Comment by glmcdona** [comment]
Great find with this bug. This will make a big difference when fixed to the trained agents!
