### ISSUE TITLE
[Discussion] Support mix of hardcoded and RL logic

### ISSUE THREAD

**Issue by glmcdona** [glmcdona/LuxPythonEnvGym#79]
Just noting here, that the winning imitation learning solution only applies actions to Units, not CityTiles:
https://www.kaggle.com/shoheiazuma/lux-ai-with-imitation-learning

The cities have hardcoded actions of building workers if possible, otherwise research. Adding support for this would approximately reduce the number of action decisions by ~33%, and reduce the number of actions by a couple.

Suggest we add more agent callbacks for hardcoded logic to apply that can give units actions without creating an observation. Thoughts? I think we can make it backwards compatible.

**Comment by royerk** [comment]
I wanted to try the idea when I saw that code but I don't know how to add
such a callback to use rules in certain conditions. (Could be used when
stacked units all try to go in the same direction too)
