### ISSUE TITLE
[Question] Reward calculation in example agent

### ISSUE THREAD

**Issue by nosound2** [glmcdona/LuxPythonEnvGym#83]
In [get_reward](https://github.com/glmcdona/LuxPythonEnvGym/blob/8d63a6212b5503cc27c76face66954d8e9066bce/examples/agent_policy.py#L514) function the calculations is this
```
reward_state = city_tile_count * 0.01 + unit_count * 0.001
return reward_state * (city_tile_count + unit_count)
```
What is the reason for having it squared?

**Comment by glmcdona** [comment]
No good reason. I've fixed it in my personal training scripts now to not reward square it like this. I will fix this logic to be a better example.

I was under the false impression that I if I didn't do that, I would be rewarding fewer units/cities. The reward logic gives a reward only at the start of each turn, as the number of actions per turn increases, this means more sparse reward so less reward on average. I think what matters is the mean episode total reward instead, so it doesn't need this scaling.

**Comment by royerk** [comment]
Looking forward to see how the current run will do (as of right now the kaggle notebook indicates that it's running with the updated reward function).

**Comment by glmcdona** [comment]
With that reward function, around a ~12.0 episode mean reward corresponds to around a ~800 public score.

**Comment by royerk** [comment]
An argument in favor of the CNN approach is the success of the imitation code that has been posted. I'm going down that path too at the moment.

**Comment by royerk** [comment]
@glmcdona I feel so frustrated right now. 

* My current best bot is ~850, I was based on the initial `agent_policy`. I thought I made some clever changes but I forgot to use the "clever changes" one during the long training. So it's good but thanks to a double mistake or something. Let's called it `v1`.
* I trained a new one with your update. Mean reward ~16 and it sits at ~814 in the leaderboard. Let's call it `v2`.
* Locally `v2` largely outperforms `v1`,  win rate > 60%, but in the leaderboard `v1` is still above.

I'm sure you both had similar issues, sorry for venting :-)

**Comment by nosound2** [comment]
@royerk , I only dream to have your problems, my best bot is doing 540 =)

Probably >60% win rate is not yet big enough to be reflected in the LB fast. I saw a discussion on the forum that some people complain that their agents don't get their expected scores for days.

**Comment by glmcdona** [comment]
I added an update to the example training script to the new reward function in #86, along with a couple other small updates.

@royerk, mean reward of ~16 is really good. Did you set it to deterministic or non-deterministic inference? My best one at around reward of 12 mapping to 800 rank is running on `deterministic=False`. You may want to check that?

**Comment by royerk** [comment]
> ... on `deterministic=False`. You may want to check that?

It's set to `False`, I have adopted that since your comment in a PR (thanks again).
