### ISSUE TITLE
[To improve] Towards better version control with the setup

### ISSUE THREAD

**Issue by royerk** [glmcdona/LuxPythonEnvGym#93]
Hi,

Running additional tests this morning. With `gym==0.17.0` I keep getting an issue about `Box has no attribute shape`, this disappears with `gym==0.19.0`. To avoid any issue it should be set to `0.19.0` in the setup (not only `<0.20.0`).

I was able to trigger the python version warning even while using python 3.7.  (`Warning, you are using python3.7, to submit to kaggle consider switching to python3.7`). This is not as helpful as it should be, need fixing.

@glmcdona can you assign the issue to me please?

**Comment by kevinu3d** [comment]
Can be closed now :-)
